name: sstats
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  #- xarray # xhistogram, xrft dependency
  - dask
  - dask-jobqueue
  - python-graphviz
  - zarr
  - netcdf4
  - jupyterlab
  - ipywidgets
  - seaborn
  - scikit-learn
  - scikit-gstat
  - statsmodels
  - sympy
  #pytorch
  #emd
  - xhistogram
  - xrft
  - pywavelets
  - pip
  - pip:
    - kymatio
